name: Publish Book of Ryan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
      
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build "Ryan online"
        run: |
          cd /home/runner/work/ryan/ryan/ryan-web/ryan-online
          make build
          cp -r ./dist /home/runner/work/ryan-online

      - name: MdBook build
        run: |
          cd /home/runner/work/ryan/ryan/book-of-ryan
          mdbook build
          cp -r ./book /home/runner/work/book-of-ryan

      - name: Checkout GitHub Pages repo
        run: |
          cd /home/runner/work  
          git clone https://${{ secrets.GH_PAT }}@github.com/tokahuke/tokahuke.github.io.git
      
      - name: Copy MdBook into GitHub pages
        run: |
          cd /home/runner/work/tokahuke.github.io
          mkdir -p ./static/book-of-ryan
          rm -rf ./static/book-of-ryan
          mv /home/runner/work/book-of-ryan ./static/book-of-ryan
      
      - name: Copy "Ryan online" into GitHub pages
        run: |
          cd /home/runner/work/tokahuke.github.io
          mkdir -p ./static/ryan-online
          rm -rf ./static/ryan-online
          mv /home/runner/work/ryan-online ./static/ryan-online
      
      - name: Commit and push to GitHub pages
        run: |
          cd /home/runner/work/tokahuke.github.io
          git config --global user.email "noreply@users.github.io"
          git config --global user.name "Pedro B Arruda"
          git add static
          git commit -m 'pushing Ryan to GitHub Pages' || echo "it's ok to have nothing..."
          git push
