name: Publish Book of Ryan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: MdBook build
        run: |
          cd book-of-ryan
          mdbook build
          cp -r ./book /home/runner/work/book-of-ryan

      - name: Copy artifacts into GitHub Pages repo
        run: |
          cd /home/runner/work
          git clone https://${{ secrets.GH_PAT }}@github.com/tokahuke/tokahuke.github.io.git
          cd tokahuke.github.io
          mkdir -p ./static/book-of-ryan
          rm -rf ./static/book-of-ryan
          mv /home/runner/work/book-of-ryan ./static/
          git config --global user.email "noreply@users.github.io"
          git config --global user.name "Pedro B Arruda"
          git add static
          git commit -m 'pushing Book of Ryan to GitHub Pages'
          git push
