name: Publish Book of Ryan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: MdBook build
        run: |
          cd book-of-ryan
          mdbook build
          cp -r ./book /home/runner/work/book

      - name: Checkout GitHub Pages repo
        uses: actions/checkout@v2
        with:
          repository: tokahuke/tokahuke.github.io
      
      - name: Copy artifacts into GitHub Pages repo
        run: |
          mkdir -p ./static/book-of-ryan
          cp -r /home/runner/work/book ./static/book-of-ryan
          git add static
          git commit -m 'pushing Book of Ryan to GitHub Pages'
          git push
