name: Publish Book of Ryan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Checkout GitHub Pages repo
        uses: actions/checkout@v2
        with:
          repository: tokahuke/tokahuke.github.io
      
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: MdBook build
        run: |
          cd /home/runner/work/ryan/book-of-ryan
          mdbook build
          cd /home/runner/work/tokahuke.github.io
          cp -r /home/runner/work/ryan/book-of-ryan/book \
            /home/runner/work/tokahuke.github.io/book-of-ryan/book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book-of-ryan/book
          output-dir: ./book-of-ryan
