name: Publish Bindings to different programming languages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  python:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions: write-all
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Build wheels with Docker
        run: |
          cd ryan-python
          make user=tokahuke password=${{ secrets.PYPI_PASSWORD }} publish
  
  cargo-install:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Cargo login
        run: |
          echo ${{ secrets.CRATES_IO_TOKEN }} | cargo login
      
      - name: Cargo Publish
        run: |
          cargo publish -p ryan-cli
  
  javascript-web:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: wasm32-unknown-unknown
  
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
      - name: Build JS bindings with Wasm Pack
        run: |
          cd ryan-web
          make build
          cp readme.md ./pkg/readme.md
      
      - name: Publish to NpmJS.org
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ryan-web/pkg/package.json
          check-version: true

  javascript-node:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: wasm32-unknown-unknown
  
      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      
      - name: Build JS bindings with Wasm Pack
        run: |
          cd ryan-js
          make build
          cp readme.md ./pkg/readme.md

      - name: Publish to NpmJS.org
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ryan-js/pkg/package.json
          check-version: true
