name: Publish Bindings to different programming languages

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  python:
    runs-on: ubuntu-latest
    permissions: write-all
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Build wheels wiht Docker
        run: |
          cd ryan-python
          make user=tokahuke password=${{ secrets.PYPI_PASSWORD }} publish
