name: Publish release

on:
  push:
    tags:
    - "v*"
  
jobs:
  release:
    permissions: write-all
    name: Build release artifacts
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: 
        - x86_64-unknown-linux-musl
        - x86_64-pc-windows-gnu
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        target: ${{ matrix.target }}
    
    - name: Build target
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target ${{ matrix.target }}
    
    - name: Set exec extension for windows
      shell: bash
      run: |
        echo "EXTENSION=.exe" >> $GITHUB_ENV
      if: ${{ matrix.target == "x86_64-pc-windows-gnu" }} 

    - name: Set exec extension for Linux
      shell: bash
      run: |
        echo "EXTENSION=" >> $GITHUB_ENV
      if: ${{ matrix.target == "x86_64-pc-windows-gnu" }} 


    - name: Package
      shell: bash
      run: |
        cd target/${{ matrix.target }}/release          
        cp ryan${{ env.EXTENSION }} ../../../ryan@${{ matrix.target }}${{ env.EXTENSION }}
        cd -
    
    - name: Publish
      uses: fnkr/github-action-ghr@v1
      with:
        files: 'ryan@*'
      env:
        GHR_COMPRESS: zip
        GHR_PATH: ryan@${{ matrix.target }}${{ env.EXTENSION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
